name: SellWands
version: ${project.version}
main: net.projectsolaris.sellwands.SellWands
api-version: 1.15
authors: [GingeyBook]
description: Project Solaris Skyblock server sell wands
website: projectsolaris.net
commands:
  si:
    description: Gives sell items